# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.2
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Jeremy Tuloup
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: frontend
labextension_name: lumino-polling-example
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension to demonstrate the Lumino Polling
python_name: lumino_polling_example
repository: https://github.com/jtpio/lumino-polling-example
test: false
viewer_name: ''

